# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Zonar' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Zonar
    pod 'Firebase/Core'
    # pod 'Firebase/AdMob'
    pod 'Firebase/Messaging'
    pod 'Firebase/Database'	
    # pod 'Firebase/Invites'
    # pod 'Firebase/DynamicLinks'
    pod 'Firebase/Crash'
    # pod 'Firebase/RemoteConfig'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'

  target 'ZonarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZonarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
